var massJohn=50;
var heightJohn=2.7;
var massMark=60;
var heightMark=6.5;
var BMIMark=50/(2.7*2.7);
console.log(BMIMark);
var BMIJohn=60/(6.5*6.5);
console.log(BMIJohn);
var highermarksBMI=BMIMark>BMIJohn;
console.log("Is Mark's BMI higher than John's?" +highermarksBMI);